export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password/:token",
  REGISTER: "/register",
  PLANS: "/plans",
  PAYMENT: "/payment",
  ANIME: "/anime",
  TV_SHOWS: "/tvshows",
  OFFERS: "/offers",
  WISHLIST: "/wishlist",
  MOVIES: "/movies",
  SERIES: "/series",
  MOVIE_DETAILS: "/movie/:id",
  WATCH_MOVIE: "/watch/:id",
  PROFILE: "/profile",
  EDIT_PROFILE: "/edit-profile",
  DASHBOARD: "/dashboard",
  ADMIN_LOGIN: "/admin-login",
  ADMIN_PROFILE: "/admin-profile",
  ADMIN_DASHBOARD: "/admin",
  ADMIN_MOVIES: "/admin/movies",
  ADMIN_SERIES: "/admin/series",
  ADMIN_USERS: "/admin/users",
  ADMIN_PLANS: "/admin/plans",
  ADMIN_OFFERS: "/admin/offers",
  ADMIN_PAYMENTS: "/admin/payments",
};

export const ROUTE_HELPERS = {
  MOVIE_DETAILS: (id) => `/movie/${id}`,
  WATCH_MOVIE: (id) => `/watch/${id}`,
  RESET_PASSWORD: (token) => `/reset-password/${token}`,
};

