export const STORAGE_KEYS = {
  TOKEN: "token",
  CURRENT_USER: "currentUser",
  CHECKOUT_PENDING: "checkoutPending",
  WATCHLIST: "watchlist",
  WISHLIST: "wishlist",
  MOVIE_PROGRESS_PREFIX: "movieProgress_",
  RECENTLY_WATCHED: "recentlyWatched",
  CONTINUE_WATCHING: "continueWatching",
  SUBSCRIPTION_END_DATE: "subscriptionEndDate",
  SUBSCRIPTION_PLAN: "subscriptionPlan",
  SELECTED_PLAN: "selectedPlan",
  PENDING_PLAN: "pendingPlanSelection",
  PAYMENT_STATUS: "paymentStatus",
};
